version: "3.9"

networks:
  cattle-network:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: cattle-db
    environment:
      - POSTGRES_DB=cattledb
      - POSTGRES_USER=cattleuser
      - POSTGRES_PASSWORD=cattlepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - cattle-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cattle-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/resnet_best.pth
      - METADATA_PATH=/app/data/breed_metadata.csv
      - CLASSES_PATH=/app/models/classes.txt
      - MODEL_NAME=resnet
      - MODEL_VERSION=v2.0
      - DATABASE_URL=postgresql://cattleuser:cattlepass@cattle-db:5432/cattledb
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - cattle-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cattle-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cattle-network

volumes:
  postgres_data:
